# render.yaml
services:
  - type: web
    name: salesflow-backend
    region: frankfurt
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: echo "Используется Dockerfile"
    envVars:
      - key: SECRET_KEY
        value: your-django-secret-key-change-it-123456789
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: salesflow-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: salesflow-db
          property: connectionString
    databases:
      - name: salesflow-db

  - type: web
    name: salesflow-frontend
    region: frankfurt
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    publishCommand: cd frontend/dist
